trigger:
  branches:
    include: ["master", "develop*", "release*", "refs/tags/*" ]
  paths:
    exclude: [ "doc", "*.md", ".gitignore" ]

jobs:
- job: UNFLoader_Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
      echo Add Linux dependencies
      sudo apt-get install libncurses5-dev libncursesw5-dev libftdi1-dev libusb-1.0-0-dev libudev-dev
      
      cd $BUILD_SOURCESDIRECTORY
      
      echo Build App
      cd ./UNFLoader/
      ls
      make -f Makefile
      chmod +x UNFLoader
      #copy to artifacts directory
      mkdir artifact
      mv UNFLoader artifact
      mv installer_linux.sh artifact
    displayName: 'Build Program'
    continueOnError: false

  # Publish build artifacts to Azure Artifacts/TFS or a file share
  - task: PublishBuildArtifacts@1
    displayName: Publish Build Artifacts
    inputs:
      pathtoPublish: '$(Build.SourcesDirectory)/UNFLoader/artifact/' 
      artifactName: 'unfloader-linux' 
      publishLocation: 'Container' # Options: container, filePath
      parallel: true # Optional

- job: UNFLoader_Windows
  pool:
    vmImage: 'windows-2019'
  steps:
       
  # Visual Studio build
  # Build with MSBuild and set the Visual Studio version property
  - task: VSBuild@1
    inputs:
      solution: '**\*.sln' 
      configuration: 'Release'
      vsVersion: '16.0' # Optional. Options: latest, 16.0, 15.0, 14.0, 12.0, 11.0
      msbuildArchitecture: 'x86' # Optional. Options: x86, x64


  # Publish build artifacts to Azure Artifacts/TFS or a file share
  - task: PublishBuildArtifacts@1
    displayName: Publish Build Artifacts
    inputs:
      pathtoPublish: '$(Build.SourcesDirectory)/UNFLoader/Release/UNFLoader.exe'
      #pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'unfloader-windows' 
      publishLocation: 'Container' # Options: container, filePath
      #targetPath: # Required when publishLocation == FilePath
      parallel: true # Optional
      #parallelCount: # Optional

      
- job: UFNLoader_macOS
  pool:
    vmImage: 'macOS-latest'
  steps:
  - script: |
      export HOMEBREW_CELLAR=$(brew --cellar) 
      export HOMEBREW_PREFIX=$(brew --prefix)
      echo Installing Prerequisites
      brew install libftdi

      echo Build macOS App
      cd ./UNFLoader/
      make
      chmod +x UNFLoader
      cd ..
    displayName: 'Build Program'
    continueOnError: false
  # Publish build artifacts to Azure Artifacts/TFS or a file share
  - task: PublishBuildArtifacts@1
    displayName: Publish Build Artifacts
    inputs:
      pathtoPublish: '$(Build.SourcesDirectory)/UNFLoader/UNFLoader'
      artifactName: 'unfloader-macOS' 
      publishLocation: 'Container' # Options: container, filePath
      parallel: true # Optional
